version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment: 
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=banking
      - KEYCLOAK_CLIENT_ID=banking-api
      - KEYCLOAK_ISSUER_LOCAL=http://localhost:8080/realms/banking
      - KEYCLOAK_ISSUER_DOCKER=http://keycloak:8080/realms/banking
      - KEYCLOAK_JWKS_URI=http://host.docker.internal:8080/realms/banking/protocol/openid-connect/certs
      - DEBUG=keycloak-connect:*
    depends_on:
      - db
      - keycloak

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ebankuser
      POSTGRES_PASSWORD: ebankpass
      POSTGRES_DB: ebankdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  pgdata:
